"""initial migration

Revision ID: ed25df413fbb
Revises: 
Create Date: 2022-04-27 15:02:44.912616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed25df413fbb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('password', sa.LargeBinary(), nullable=True),
    sa.Column('registered_on', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('video_vault',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=225), nullable=False),
    sa.Column('thumbnail', sa.String(length=225), nullable=False),
    sa.Column('duration', sa.String(length=80), nullable=False),
    sa.Column('added_by', sa.Integer(), nullable=False),
    sa.Column('added_on', sa.DateTime(), nullable=False),
    sa.Column('last_played_on', sa.DateTime(), nullable=True),
    sa.Column('play_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['added_by'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('video_id')
    )
    op.create_table('currently_playing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vault_id', sa.Integer(), nullable=False),
    sa.Column('added_on', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['vault_id'], ['video_vault.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('initial_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vault_id', sa.Integer(), nullable=False),
    sa.Column('added_on', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['vault_id'], ['video_vault.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('initial_entry')
    op.drop_table('currently_playing')
    op.drop_table('video_vault')
    op.drop_table('Users')
    # ### end Alembic commands ###
